/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Service.StaffDAO;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.util.concurrent.atomic.AtomicInteger;
import Model.objectToInt;
import Service.CongDAO;

/**
 *
 * @author admin
 */
public class ChamCong extends javax.swing.JPanel {

    DefaultTableModel model;
    private StaffDAO stdao = new StaffDAO();
    private CongDAO cdao = new CongDAO();

    /**
     * Creates new form ChamCong
     */
    public ChamCong() throws SQLException {
        initComponents();
        model = (DefaultTableModel) tablecong.getModel();
        displayData();
        ArrayList<Integer> staffIds = stdao.getStaffIds();
        ArrayList todayCongIds = cdao.getTodayCongIds();
        System.out.println(staffIds);
        System.out.println(todayCongIds);
        staffIds.forEach(id -> {
            if (!todayCongIds.contains(id)) {
                try {
                    cdao.addCong(id);
                } catch (SQLException ex) {
                    Logger.getLogger(ChamCong.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

    }

    private void displayData() throws SQLException {
        model.setRowCount(0);
        ResultSet rs = cdao.getTodayCong();
        try {
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("cong_id"),
                    rs.getInt("staff_id"),
                    rs.getString("staff_name"),
                    rs.getInt("cong") == 0 ? false : true
                }
                );
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablecong = new javax.swing.JTable();

        tablecong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ma cong", "Ma nhan vien", "Ten nhan vien", "Cong"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablecong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablecongMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablecong);

        jScrollPane2.setViewportView(jScrollPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

    }// </editor-fold>//GEN-END:initComponents

    private void tablecongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablecongMouseClicked
        // TODO add your handling code here:
        boolean cong;
        //System.out.println(tablecong.getRowCount());
        for (int i = 0; i < tablecong.getRowCount(); i++) {
            
            //System.out.println(i);
            try {
                System.out.println(Boolean.valueOf(tablecong.getValueAt(i, 3).toString()));
                cong = Boolean.valueOf(tablecong.getValueAt(i, 3).toString());
                cdao.update(Integer.valueOf(tablecong.getValueAt(i, 0).toString()), cong);
            } catch (SQLException | NullPointerException ex) {
                Logger.getLogger(ChamCong.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tablecongMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ChamCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ChamCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ChamCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ChamCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                try {
//                    new ChamCong().setVisible(true);
//                } catch (SQLException ex) {
//                    Logger.getLogger(ChamCong.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tablecong;
    // End of variables declaration//GEN-END:variables
}
