/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Service.MembershipDAO;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author maith
 */
public class MembershipInte extends javax.swing.JPanel {

    MembershipDAO mmbs = new MembershipDAO();
    private LocalDate ngayhethan;
    private LocalDate ngayhientai;

    /**
     * Creates new form MembershipInte
     */
    public MembershipInte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtten = new javax.swing.JTextField();
        txtsdt = new javax.swing.JTextField();
        btnnsignin = new javax.swing.JButton();

        jLabel1.setText("Tên khách hàng");

        jLabel2.setText("Số điện thoại");

        btnnsignin.setText("Đăng ký");
        btnnsignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnsigninActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnnsignin)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtten, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(txtsdt))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnnsignin)
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnnsigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnsigninActionPerformed
        // TODO add your handling code here:
        String ten = txtten.getText();
        String sdt = txtsdt.getText();
        ngayhientai = LocalDate.now();
        String regexphone = "^[0-9]${9}";

        if (ten.isEmpty() || sdt.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
            return;
        }
        if (sdt.matches(regexphone)) {
            JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ");
            return;
        }
//    String thoiHanSelected = (String) cbboxexpirday.getSelectedItem();
//    int monthsToAdd = Integer.parseInt(thoiHanSelected.split(" ")[0]);

//    ngayhethan = ngayhientai.plusMonths(monthsToAdd);
        String securityCode = "MB" + String.format("%02d", (int) (Math.random() * 100));

//    LocalDateTime localDateTime = ngayhethan.atStartOfDay();
//    Timestamp expirationDate = Timestamp.valueOf(localDateTime.atZone(ZoneId.systemDefault()).toLocalDateTime());
//
//    String rankName = (String) jComboBox1.getSelectedItem();
        MembershipDAO mmbs = new MembershipDAO();
        //boolean isAdded = mmbs.add(ten, sdt, securityCode, rankName, expirationDate);
        if(mmbs.isExist(sdt)) {
            JOptionPane.showMessageDialog(this, "Hội viên đã tồn tại");
            return;
        }
        
        boolean isAdded = mmbs.add(ten, sdt, securityCode);
        if (isAdded) {
            JOptionPane.showMessageDialog(this, "Đăng ký thành công");
        } else {
            JOptionPane.showMessageDialog(this, "Đăng ký thất bại");
        }
    }//GEN-LAST:event_btnnsigninActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnnsignin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtsdt;
    private javax.swing.JTextField txtten;
    // End of variables declaration//GEN-END:variables
}
