/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Service.VoucherDAO;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
/**
 *
 * @author ADMIN
 */
public class Voucher extends javax.swing.JPanel {
    VoucherDAO voucherdao = new VoucherDAO();
    /**
     * Creates new form Voucher
     */
    DefaultTableModel Model;
    public Voucher() {
        initComponents();
        Model = (DefaultTableModel) tblvoucher.getModel();
        loaddata();
    }
    public void loaddata() {
        Model.setRowCount(0);
        ResultSet rs = voucherdao.hienthi();
        try {
            while (rs.next()) {
                Model.addRow(new Object[]{
                    rs.getInt("voucher_id"),
                    rs.getString("start_date"),
                    rs.getString("end_date"),
                    rs.getInt("product_id"),
                    rs.getFloat("new_product_price")
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtstartdate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtenddate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblvoucher = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtmasp = new javax.swing.JTextField();

        jLabel1.setText("Ngày bắt đầu:");

        txtstartdate.setForeground(new java.awt.Color(128, 128, 128));
        txtstartdate.setText("dd/MM/yyyy");
        txtstartdate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtstartdateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtstartdateFocusLost(evt);
            }
        });
        txtstartdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstartdateActionPerformed(evt);
            }
        });

        jLabel2.setText("Ngày Kết Thúc:");

        txtenddate.setForeground(new java.awt.Color(128, 128, 128));
        txtenddate.setText("dd/MM/yyyy");
        txtenddate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtenddateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtenddateFocusLost(evt);
            }
        });
        txtenddate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtenddateActionPerformed(evt);
            }
        });

        jLabel3.setText("Giá sau khi áp dụng");

        txtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("VOUCHER");

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblvoucher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Voucher", "Ngày bắt đầu", "Ngày hết hiệu lực", "Mã Sản Phẩm áp dụng", "Giá Sản Phẩm"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblvoucher);

        jLabel5.setText("Mã Sản Phẩm:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(txtstartdate, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(txtenddate, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(txtmasp, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(124, 124, 124))
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtstartdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtmasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtenddate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(70, 70, 70)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
    String startStr = txtstartdate.getText().trim();
    String endStr = txtenddate.getText().trim();
    int productId = Integer.parseInt(txtmasp.getText().trim());
    float newPrice = Float.parseFloat(txtprice.getText().trim());
    if(newPrice >= 0){
    }else{
    JOptionPane.showMessageDialog(this, "Gia khong hop le");
    return;
    }
    // Định dạng ngày người dùng nhập: dd/MM/yyyy
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    sdf.setLenient(false);

    Timestamp start_date = new Timestamp(sdf.parse(startStr).getTime());
    Timestamp end_date = new Timestamp(sdf.parse(endStr).getTime());
    if(start_date.before(end_date)){
    }else{
        JOptionPane.showMessageDialog(this, "ngay khong hop le");
    return;
    }
    boolean success = voucherdao.add(start_date, end_date, productId, newPrice);
    if (success) {
        JOptionPane.showMessageDialog(this, "Thêm voucher thành công!");
        loaddata();
    } else {
        JOptionPane.showMessageDialog(this, "Thêm voucher thất bại!");
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Lỗi nhập liệu! Hãy nhập đúng định dạng: dd/MM/yyyy và kiểm tra số liệu khác.");
    e.printStackTrace();
        }

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtstartdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstartdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstartdateActionPerformed

    private void txtstartdateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtstartdateFocusGained
        // TODO add your handling code here:
        if(txtstartdate.getText().equals("dd/MM/yyyy")) {
            txtstartdate.setForeground(Color.BLACK);
            txtstartdate.setText("");
        }
    }//GEN-LAST:event_txtstartdateFocusGained

    private void txtstartdateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtstartdateFocusLost
        // TODO add your handling code here:
        if(txtstartdate.getText().equals("")) {
            txtstartdate.setForeground(Color.GRAY);
            txtstartdate.setText("dd/MM/yyyy");
        }
    }//GEN-LAST:event_txtstartdateFocusLost

    private void txtenddateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtenddateFocusGained
        // TODO add your handling code here:
        if(txtenddate.getText().equals("dd/MM/yyyy")) {
            txtenddate.setForeground(Color.BLACK);
            txtenddate.setText("");
        }
    }//GEN-LAST:event_txtenddateFocusGained

    private void txtenddateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtenddateFocusLost
        // TODO add your handling code here:
        if(txtenddate.getText().equals("")) {
            txtenddate.setForeground(Color.GRAY);
            txtenddate.setText("dd/MM/yyyy");
        }
    }//GEN-LAST:event_txtenddateFocusLost

    private void txtenddateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtenddateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtenddateActionPerformed

    private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtpriceActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Voucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Voucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Voucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Voucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Voucher().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblvoucher;
    private javax.swing.JTextField txtenddate;
    private javax.swing.JTextField txtmasp;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtstartdate;
    // End of variables declaration//GEN-END:variables
}
